### ISSUE TITLE
renderTemplateSource produces an empty string

### ISSUE THREAD

**Issue by AndyCJ** [rniemeyer/knockout-amd-helpers#37]
`renderTemplateSource` in Knockout calls the text function from the `templateSource` and then uses it right away to create HTML Elements.

[nativeTemplateEngine.js#L15](https://github.com/knockout/knockout/blob/241c26ca82e6e4b3eaee39e3dc0a92f85bc1df0c/src/templating/native/nativeTemplateEngine.js#L15)

This doesn't work with with the text function in Knockout AMD Helpers as the text is loaded asynchronously.

[amdTemplateEngine.js#L24](https://github.com/rniemeyer/knockout-amd-helpers/blob/master/src/amdTemplateEngine.js#L24)

And while that request is being made the current template is returned, which is an empty string.

[amdTemplateEngine.js#L37](https://github.com/rniemeyer/knockout-amd-helpers/blob/master/src/amdTemplateEngine.js#L37)

I tried to figure out if this could be corrected, but the function chain is synchronous.

Is there a work around for this?

I assume pre-loading the templates would work as long as I gave them enough time to return, but I'd rather have the lazy loading.

Another option might be creating `renderTemplateSourceAsync`. I don't think that would work with existing ko code, but it'd work for my use case.

**Comment by rniemeyer** [comment]
@AndyCJ - are you seeing a specific problem with lazy loading templates? That is generally how I have used `knockout-amd-helpers` (at least for a dev build).  When the template content becomes available, then the template/module binding is re-evaluated. I may be misunderstanding your comment/issue, but I am happy to help you sort it out. Thanks!

**Comment by AndyCJ** [comment]
@rniemeyer I was using some third party code that makes a direct call to `renderTemplateSource`, so there's no template binding.

This is no longer an issue for me as I've move on to using a different approach.

**Comment by imtonyjoseph** [comment]
@rniemeyer @AndyCJ Hi there, 
I am facing an issue which is pretty similar to what is mentioned in the above issue.

My code internally calls renderTemplateSource and the text function returns an empty string (templateText) in the code below. Since require is fetching the file asynchronously.

`var templateText = templateSource['text']();`


This empty text is then returned to be appended to the template HTML which I am trying to load, which looks something like this 
`<script type="text/html" id="EDIT_CELL_TEMPLATE">
    <div data-bind="
        attr: {
            style: $parent.cellStyle($cellContext, ''),
            css: $parent.cellClass($cellContext),
        },
        template: {
            data: $parent.inlineEditViewModel,
            name: $parent.getModuleInfo().viewName
        }">
    </div>
</script>`

The above template resolves into an input component.

Although the UI loads up perfectly, the JET internal code is trying to render the above script and focus on the input component which the template resolves to. But since the function renderTemplateSource returns empty text while trying to resolve the above templates nodes, the HTML does not contain any focusable element and is left with only the non-focusable elements in the script above. This prevents the JET component from getting into a certain _edit mode_ which causes undesired behaviour.

Is there any way we could work around this issue?
Any help would be deeply appreciated.
Thanks
